export const SET_ALERT = 'SET_ALERT';
export const REM_ALERT = 'REM_ALERT';
export const REG_SUCC = 'REG_SUCC';
export const REG_FAIL = 'REG_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const LOGIN_SUCC = 'LOGIN_SUCC';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const EDITED_PROFILE = 'EDITED_PROFILE';
export const ERROR_IN_UPDATING_PROFILE = 'ERROR_IN_UPDATING_PROFILE';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const ERROR_IN_ADDING_EDUCATION = 'ERROR_IN_ADDING_EDUCATION';
export const GET_EDUCATION_LIST = 'GET_EDUCATION_LIST';
export const ERROR_IN_GETTING_EDUCATIONS = 'ERROR_IN_GETTING_EDUCATIONS';
export const DELETED_EDUCATION = 'DELETED_EDUCATION';
export const FAILED_TO_DELETE_EDUCATION = 'FAILED_TO_DELETE_EDUCATION';
export const ADD_NEW_JOB = 'ADD_NEW_JOB';
export const ERROR_ADDING_JOB = 'ERROR_ADDING_JOB';
export const ERROR_GETTING_JOB = 'ERROR_GETTING_JOB';
export const GOT_JOBS = 'GOT_JOBS';
export const ERROR_LOADING_JOB = 'ERROR_LOADING_JOB';
export const LOADED_JOB = 'LOADED_JOB';
export const DELETE_JOB = 'DELETE_JOB';
export const ERROR_WHILE_DELETING_JOB ='ERROR_WHILE_DELETING_JOB';
export const EDITED_JOB= 'EDITED_JOB';
export const FAILED_EDITING_JOB = 'FAILED_EDITING_JOB';
export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const FAILED_TO_GET_ALL_JOBS = 'FAILED_TO_GET_ALL_JOBS';
export const ADDED_NEW_APPLICATION= 'ADDED_NEW_APPLICATION';
export const FAILED_TO_ADD_NEW_APPLICATION = 'FAILED_TO_ADD_NEW_APPPLICATION';
export const GOT_ALL_APPLICATION='GOT_ALL_APPLICATION';
export const FAILED_TO_GET_ALL_APPLICATION='FAILED_TO_GET_ALL_APPLICATION';
export const GOT_ALL_APPLICATION_STATUS='GOT_ALL_APPLICATION_STATUS';
export const FAILED_TO_GET_ALL_APPLICATION_STATUS='FAILED_TO_GET_ALL_APPLICATION_STATUS';


// Knowing the type of the user

export const Applicant = 'Applicant';
export const Recruiter = 'Recruiter'
